repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: \.gitignore
        args: ["--unique"]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.8.0
    hooks:
      - id: eslint
        additional_dependencies:
          - "@eslint/eslintrc@3.1.0"
          - "@eslint/js@9.8.0"
          - "eslint@9.8.0"
          - "globals@15.8.0"

  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo-clippy
        entry: |
          .ci/xargify.py
            -q
            -f warning
            --
            cargo clippy
              --manifest-path {}
              --color=always
              --
              -D warnings
              -D clippy::dbg_macro
              -A clippy::uninlined-format-args
            ---
        require_serial: true
        language: script
        files: "Cargo.toml$"
        always_run: true
      - id: cargo-fmt
        name: cargo-fmt
        entry: |
          .ci/xargify.py
            --
            cargo fmt --manifest-path {} -- -l ---
        require_serial: true
        language: script
        files: "Cargo.toml$"
        always_run: true

exclude: '2021/08/python_golf/solution\.py$|input(_test.*)?$'
