control_brace_style = "ClosingNextLine"
force_multiline_blocks = false
imports_layout = "Vertical"
match_arm_blocks = false
merge_imports = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
