name: solution

dependencies:
  - base >= 4.7 && < 5
  - hmatrix

default-extensions:
  - LambdaCase
  - ParallelListComp
  - DeriveFunctor
  - Strict

ghc-options:
  -Wall
  -Wextra
  -O2
  -fllvm

executables:
  solution:
    source-dirs:      src
    main:             Main.hs
