[package]
name = "md5"
version = "0.1.0"
authors = ["narpfel <narpfel@gmx.de>"]
edition = "2021"

[dependencies]
byteorder = "1"
memmap2 = "0.9.3"
ct-python = "0.5"

[profile.release]
lto = true
codegen-units = 1
