[package]
name = "md5"
version = "0.1.0"
authors = ["narpfel <narpfel@gmx.de>"]
edition = "2018"

[dependencies]
byteorder = "1"
memmap = "0.7"
ct-python = "0.5"

[profile.release]
lto = true
codegen-units = 1
