name:                solution
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - matrix
  - vector
  - composition
  - au

default-extensions:
  - ParallelListComp
  - Strict

executables:
  solution:
    source-dirs:      src
    main:             Main.hs
