name: solution

dependencies:
  - base >= 4.7 && < 5
  - lens
  - mtl

default-extensions:
  - LambdaCase
  - ParallelListComp
  - DeriveFunctor
  - TemplateHaskell

ghc-options:
  -Wall
  -Wextra
  -O2

executables:
  solution:
    source-dirs:      src
    main:             Main.hs
