[package]
name = "solution"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[features]
visualise = []

[dependencies]
graph = { path = "../../2019/18/graph" }
itertools = "0.10"
