name:                solution

dependencies:
  - base >= 4.7 && < 5
  - au

ghc-options:
  -Wall
  -Wextra
  -O2
  -optc-O3
  -fllvm

executables:
  solution:
    source-dirs:      src
    main:             Main.hs
