[package]
name = "solution"
version = "0.1.0"
authors = ["narpfel <narpfel@gmx.de>"]
edition = "2021"

[dependencies]
generic-array = "0.12"
md5 = { path = "md5" }

[dependencies.arraydeque]
version = "0.4"
features = ["use_generic_array"]

[profile.release]
lto = true
codegen-units = 1
