name: cpu

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - vector
  - au

default-extensions:
  - LambdaCase
  - ParallelListComp
  - DeriveFunctor
  - RecordWildCards

ghc-options:
  -Wall
  -Wextra
  -O2
  -fllvm

library:
  source-dirs:
    src
