name: solution

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - MultiWayIf

ghc-options:
  -Wall
  -Wextra
  -O2

executables:
  solution:
    source-dirs:      src
    main:             Main
