name: solution

dependencies:
  - base >= 4.7 && < 5
  - extra

default-extensions:
  - LambdaCase
  - ParallelListComp
  - DeriveFunctor
  - RecordWildCards

ghc-options:
  -Wall
  -Wextra
  -O2

executables:
  solution:
    source-dirs:      src
    main:             Main.hs
