[package]
name = "solution"
version = "0.1.0"
edition = "2024"

[dependencies]
graph = { path = "../../../2019/18/graph" }
rustc-hash = "2.1.0"

[profile.release]
lto = true
codegen-units = 1
debug = 2
