name:                solution
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers
  - au

default-extensions:
  - LambdaCase

executables:
  solution:
    source-dirs:      src
    main:             Main.hs
