name: pre-commit

on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
